### ISSUE TITLE
publish scalajs-pickling-play-json for Scala 2.11

### ISSUE THREAD

**Issue by antonkulaga** [scala-js/scala-js-pickling#3]
Unfortunately scalajs-pickling-play-json is published only for Scala 2.10 (while scalajs-pickling is published for both 2,10/2.11). 
Please, publish  scalajs-pickling-play-json for 2.11 as it blocks migration to Scala 2.11

**Comment by sjrd** [comment]
Note-to-self: apparently Play 2.3 has been cross-compiled for 2.11, so it should be possible to do so by upgrading our dependency to Play.

**Comment by sjrd** [comment]
Fixed in 58156e1b16bd26e3523a453c55d94cc5f5a140e8
You can use 0.4-SNAPSHOT with Scala.js 0.5.0-RC1.
