### ISSUE TITLE
Threadsafe?

### ISSUE THREAD

**Issue by phlegmaticprogrammer** [scala-js/scala-js-pickling#7]
This is not really an issue, but a question. Is registering picklers thread-safe? For example, in 

```
class APIServlet extends HttpServlet {

  registerPicklers()

 override def doPost(req : HttpServletRequest, resp : HttpServletResponse) {
   ...
 }
```

   }

where `registerPicklers` makes calls to PicklerRegistry.register, is that OK, or do I have to take care of thread-safety myself, given that multiple instances of APIServlet may run at the same time within the same JVM? Also, I probably should make sure that only one call to registerPicklers is issued per JVM instance?

**Comment by sjrd** [comment]
No, registering is not thread-safe. And yes, it's better to only register once.

Using a registry for pickling and unpickling from different threads is safe.

**Comment by phlegmaticprogrammer** [comment]
OK, thanks.
